apiVersion: v1
kind: Service
metadata:
  name: pipeline-svc
  labels:
    {{- include "mlops-platform.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mlops-platform.selectorLabels" (dict "component" "pipeline-svc") | nindent 4 }}
  ports:
    - port: {{ .Values.pipelineSvc.port }}
      targetPort: {{ .Values.pipelineSvc.port }}
      protocol: TCP
