apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    {{- include "mlops-platform.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.apiGateway.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
